# Explainable Customer Churn Prediction and Retention Strategy
## Model Comparison: Logistic Regression, Random Forest, and XGBoost

## 1. Import Libraries
## 2. Load Data
## 3. Data Cleaning and Preparation
## 4. Exploratory Data Analysis
## 5. Feature Engineering
## 6. Train-Test Split
## 7. Logistic Regression
## 8. Random Forest
## 9. XGBoost
## 10. Model Comparison
## 11. Threshold Optimization
## 12. Explainability
## 13. Retention Strategy
## 14. Export Outputs

In [1]:
import sys
!{sys.executable} -m pip install pandas numpy scikit-learn xgboost matplotlib shap joblib openpyxl

Requirement already satisfied: pandas in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.4.2)
Requirement already satisfied: scikit-learn in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: xgboost in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.2.0)
Requirement already satisfied: matplotlib in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.10.8)
Requirement already satisfied: shap in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (0.50.0)
Requirement already satisfied: joblib in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.5.3)
Requirement already satisfied: openpyxl in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: tqdm>=4.27.0 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (4.67.3)
Requirement already satisfied: slicer==0.0.8 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (0.0.8)
Requirement already satisfied: numba==0.63.0b1 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (0.63.0b1)
Requirement already satisfied: llvmlite==0.46.0b1 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (0.46.0b1)
Requirement already satisfied: cloudpickle in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from shap) (4.15.0)
Requirement already satisfied: et-xmlfile in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from tqdm>=4.27.0->shap) (0.4.6)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

from xgboost import XGBClassifier

print("All libraries imported successfully")

C:\Users\emeka\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

All libraries imported successfully

In [3]:
df = pd.read_excel("../data/Telco_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [4]:
df.shape

(7043, 33)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

In [6]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [7]:
df_clean = df.copy()

# Drop irrelevant columns
cols_to_drop = [
    'CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
    'Lat Long', 'Latitude', 'Longitude'
]

df_clean = df_clean.drop(columns=cols_to_drop, errors='ignore')

In [8]:
# fix Total charges i.e from text to numeric
df_clean['Total Charges'] = pd.to_numeric(df_clean['Total Charges'], errors='coerce')

In [9]:
df_clean = df_clean.dropna()

In [10]:
# Changing the datatype of target variable to numeric
df_clean['Churn Value'] = df_clean['Churn Value'].astype(int)

In [11]:
# Drop leakage columns
df_clean = df_clean.drop(columns=[
    'Churn Label',
    'Churn Score',
    'Churn Reason'
], errors='ignore')

In [12]:
df_clean.shape

(1869, 21)

In [13]:
df_clean.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,...,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Value,CLTV
0,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,3239
1,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,2701
2,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,5372
3,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,5003
4,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,...,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.30,1,5340

In [14]:
df_clean.to_csv("../outputs/data/df_clean.csv", index=False)

In [15]:
df_clean.shape

(1869, 21)

In [16]:
df_clean = df.copy()

In [17]:
df_clean.shape

(7043, 33)

In [18]:
df_clean['Churn Value'] = df_clean['Churn Value'].astype(int)

In [19]:
df_clean = df_clean.drop(columns=[
    'Churn Label',
    'Churn Score',
    'Churn Reason'
], errors='ignore')

In [20]:
df_clean.shape

(7043, 30)

In [21]:
# Drop irrelevant columns
cols_to_drop = [
    'CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
    'Lat Long', 'Latitude', 'Longitude'
]

df_clean = df_clean.drop(columns=cols_to_drop, errors='ignore')

In [22]:
df_clean.shape

(7043, 21)

In [23]:
df_clean.to_csv("../outputs/data/df_clean.csv", index=False)
X = df_clean.drop('Churn Value', axis=1)
y = df_clean['Churn Value']

In [24]:
categorical_cols = X.select_dtypes(include=['object']).columns
categorical_cols

C:\Users\emeka\AppData\Local\Temp\ipykernel_12464\2870865712.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=['object']).columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Total Charges'],
      dtype='str')

In [25]:
# Apply One Hot Encoding
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

In [26]:
X_encoded.shape

(7043, 6560)

In [27]:
df_clean = df.copy()
cols_to_drop = [
    'CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
    'Lat Long', 'Latitude', 'Longitude',
    'Churn Label', 'Churn Score', 'Churn Reason'
]

df_clean = df_clean.drop(columns=cols_to_drop, errors='ignore')
df_clean['Total Charges'] = pd.to_numeric(df_clean['Total Charges'], errors='coerce')
df_clean = df_clean.dropna()
X = df_clean.drop('Churn Value', axis=1)
y = df_clean['Churn Value']
categorical_cols = X.select_dtypes(include=['object']).columns
X_encoded = pd.get_dummies(X, columns=categorical_cols, drop_first=True)
X_encoded.shape

C:\Users\emeka\AppData\Local\Temp\ipykernel_12464\2175866638.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=['object']).columns

(7032, 31)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

In [29]:
# Check Split
X_train.shape, X_test.shape

((5625, 31), (1407, 31))

In [30]:
from sklearn.preprocessing import StandardScaler

numeric_cols = X_train.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()

X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

X_train_scaled[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test_scaled[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [31]:
# Save Split data
X_train.to_csv("../outputs/data/X_train.csv", index=False)
X_test.to_csv("../outputs/data/X_test.csv", index=False)
y_train.to_csv("../outputs/data/y_train.csv", index=False)
y_test.to_csv("../outputs/data/y_test.csv", index=False)

In [32]:
X_train.shape, X_test.shape

((5625, 31), (1407, 31))

In [33]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=2000,
    class_weight='balanced',
    random_state=42
)

lr.fit(X_train_scaled, y_train)

LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)

In [34]:
# make predixtion
y_pred_lr = lr.predict(X_test_scaled)
y_proba_lr = lr.predict_proba(X_test_scaled)[:, 1]
from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_lr))

              precision    recall  f1-score   support

           0       0.90      0.71      0.79      1033
           1       0.50      0.79      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.75      1407

ROC-AUC: 0.8425798903562128

In [35]:
lr_auc = roc_auc_score(y_test, y_proba_lr)

## LR Interpretation
Good at detecting churners (high recall)
But has false positives (lower precision)

In [36]:
## Train baseline Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [37]:
## Evaluate RF

y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]
from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_rf))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1033
           1       0.64      0.51      0.57       374

    accuracy                           0.79      1407
   macro avg       0.74      0.70      0.72      1407
weighted avg       0.78      0.79      0.79      1407

ROC-AUC: 0.8323324929725475

In [ ]:
## Parameter Tuning RF
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'max_features': ['sqrt']
}

rf_model = RandomForestClassifier(
    random_state=42,
    class_weight='balanced'
)

grid_search = GridSearchCV(
    estimator=rf_model,
    param_grid=param_grid,
    cv=3,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 24 candidates, totalling 72 fits

In [ ]:
## Best Param tuning RF
best_rf = grid_search.best_estimator_
print(grid_search.best_params_)

In [ ]:
## Evaluate Tuned RF
y_pred_rf_best = best_rf.predict(X_test)
y_proba_rf_best = best_rf.predict_proba(X_test)[:, 1]

print(classification_report(y_test, y_pred_rf_best))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_rf_best))

In [ ]:
#'Train Baseline XGBoost
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

In [ ]:
## Prediction
y_pred_xgb = xgb.predict(X_test)
y_proba_xgb = xgb.predict_proba(X_test)[:, 1]

## Evaluate
from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_xgb))

In [ ]:
## XGBoost Tuning(Define the parameter grid)
from sklearn.model_selection import GridSearchCV

param_grid_xgb = {
    'n_estimators': [100, 200],
    'max_depth': [3, 4, 5],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.8, 1],
    'colsample_bytree': [0.8, 1]
}

In [ ]:
xgb_model = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)

In [ ]:
grid_xgb = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid_xgb,
    cv=3,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid_xgb.fit(X_train, y_train)

In [ ]:
best_xgb = grid_xgb.best_estimator_
print(grid_xgb.best_params_)

In [ ]:
## Evaluate Tuned Parameter XGBOOST
y_pred_xgb_best = best_xgb.predict(X_test)
y_proba_xgb_best = best_xgb.predict_proba(X_test)[:, 1]

from sklearn.metrics import classification_report, roc_auc_score

print(classification_report(y_test, y_pred_xgb_best))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_xgb_best))

## Business Decision
Although XGBoost achieved a marginally higher ROC-AUC, Random Forest was selected as the final model due to its superior balance between recall and precision. 

In a churn prediction context, missing potential churners carries a higher business cost than false positives. Random Forest achieved a significantly higher recall (0.77 vs 0.56), ensuring more at-risk customers are identified for proactive retention strategies, while maintaining a strong F1 score for overall model effectiveness.

In [ ]:
feature_importance = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': best_rf.feature_importances_
}).sort_values(by='Importance', ascending=False)

feature_importance.head()

In [ ]:
feature_importance.to_csv("../outputs/features/feature_importance.csv", index=False)

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [ ]:
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70]

threshold_results = []

for t in thresholds:
    y_pred_t = (y_proba_rf_best >= t).astype(int)
    
    precision = precision_score(y_test, y_pred_t)
    recall = recall_score(y_test, y_pred_t)
    f1 = f1_score(y_test, y_pred_t)
    
    threshold_results.append({
        'Threshold': t,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1
    })

threshold_df = pd.DataFrame(threshold_results)
threshold_df

## Choose a Threshold
A threshold of 0.50 was selected as it provides the optimal balance between precision and recall. This ensures that a significant proportion of at-risk customers are identified for intervention while maintaining manageable false positive rates, supporting efficient allocation of retention resources.

In [ ]:
## Creating a Risk Segmentation(High,medium and Low)
df_strategy = X_test.copy()

df_strategy['Actual'] = y_test
df_strategy['Churn_Probability'] = y_proba_rf_best
def assign_risk(p):
    if p >= 0.6:
        return 'High Risk'
    elif p >= 0.4:
        return 'Medium Risk'
    else:
        return 'Low Risk'

df_strategy['Risk_Level'] = df_strategy['Churn_Probability'].apply(assign_risk)

In [ ]:
## Add Business Actions
def action_map(risk):
    if risk == 'High Risk':
        return 'Immediate retention offer'
    elif risk == 'Medium Risk':
        return 'Engagement campaign'
    else:
        return 'Maintain relationship'

df_strategy['Recommended_Action'] = df_strategy['Risk_Level'].apply(action_map)

In [ ]:
df_strategy[['Churn_Probability','Risk_Level','Recommended_Action']].head()

In [ ]:
df_strategy.to_csv("../outputs/data/df_strategy.csv", index=False)

In [ ]:
import shap

In [ ]:
##Using BEST Model Ramdom Forest)
explainer = shap.TreeExplainer(best_rf)
shap_values = explainer.shap_values(X_test)

In [ ]:
import numpy as np

print(type(shap_values))
print(np.array(shap_values).shape)
print(X_test.shape)

In [ ]:
shap_values_churn = shap_values[:, :, 1]

In [ ]:
shap.summary_plot(shap_values_churn, X_test)

In [ ]:
## Bar plot version
shap.summary_plot(shap_values_churn, X_test, plot_type="bar")

In [ ]:
import matplotlib.pyplot as plt

shap.summary_plot(shap_values_churn, X_test, show=False)
plt.savefig("../outputs/figures/shap_summary.png", bbox_inches='tight')
plt.close()

In [ ]:
import joblib

joblib.dump(best_rf, "../models/random_forest_final.pkl")

In [ ]:
import pandas as pd

comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost'],
    'Precision': [0.50, 0.54, 0.64],
    'Recall': [0.79, 0.77, 0.56],
    'F1 Score': [0.61, 0.64, 0.60],
    'ROC-AUC': [0.8426, 0.8446, 0.8486]
})

In [ ]:
comparison.to_csv("../outputs/metrics/model_comparison.csv", index=False)

In [ ]:
threshold_df.to_csv("../outputs/metrics/threshold_optimization.csv", index=False)

In [ ]:
import numpy as np

shap_importance = pd.DataFrame({
    'Feature': X_test.columns,
    'Mean_SHAP_Impact': np.abs(shap_values_churn).mean(axis=0)
}).sort_values(by='Mean_SHAP_Impact', ascending=False)

shap_importance.head()

In [ ]:
shap_importance.to_csv("../outputs/features/shap_feature_importance.csv", index=False)

In [ ]:
df_full = X_encoded.copy()

df_full['Actual'] = y
df_full['Churn_Probability'] = best_rf.predict_proba(X_encoded)[:, 1]

In [ ]:
df_full.to_csv("../outputs/data/powerbi_dataset.csv", index=False)

In [ ]:
df_full = df_clean.copy()
df_full['Churn_Probability'] = best_rf.predict_proba(X_encoded)[:, 1]
def assign_risk(p):
    if p >= 0.6:
        return 'High Risk'
    elif p >= 0.4:
        return 'Medium Risk'
    else:
        return 'Low Risk'

df_full['Risk_Level'] = df_full['Churn_Probability'].apply(assign_risk)
def action_map(risk):
    if risk == 'High Risk':
        return 'Immediate retention offer'
    elif risk == 'Medium Risk':
        return 'Engagement campaign'
    else:
        return 'Maintain relationship'

df_full['Recommended_Action'] = df_full['Risk_Level'].apply(action_map)
df_full.to_csv("../outputs/powerbi_dataset.csv", index=False)